baseURL = "/"
title = "SpinDev"

theme = "puppet"

copyright = "Copyright © 2022"
paginate = 3
languageCode = "en"
defaultContentLanguage = "en"

hasCJKLanguage = true
enableInlineShortcodes = true
enableEmoji = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

disqusShortname = ""
googleAnalytics = ""

[outputs]
home = ["HTML", "JSON", "RSS"]

# prevent build failures when using Hugo's template _internal/opengraph.html 
[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[markup]
[markup.highlight]
noClasses = true
codeFences = true
guessSyntax = true
lineNos = true
lineNumbersInTable = false
style = "dracula"

[markup.goldmark.renderer]
unsafe = true

[menu]
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = -100
# [[menu.main]]
# identifier = "archive"
# name = "Archive"
# url = "/archive/"
# weight = 10
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 50

[params]
author = "SpinDev"
description = "Some insights in my work and my life."
keywords = "blog,developer,personal"
img_home = "img/home-bg.jpg"
img_404 = "img/404-bg.jpg"

useFaviconGenerator = true

custom_js = []
custom_css = [] # ["css/custom.css"]  Add your file to assets folder  [assets/css/custom.css]

[params.sidebar]
enable = true
gravatarEmail = ""
# Overwritten by your gravatar image if `gravatarEmail` is filled
avatar = "img/home-bg.jpg"
bio = "DevOps and Agile"

[params.social]
github = "Spindev"
linkedin = "Till Spindler"
rss = true

[[params.friends]]
name = "Xpirit"
url = "https://xpirit.com"

[[params.friends]]
name = "Michael Kaufmann"
url = "https://writeabout.net"

[[params.friends]]
name = "Thomas Tomow"
url = "https://tomow.de"


[[params.friends]]
name = "Michael Contento"
url = "https://michaelcontento.com"

# See https://giscus.app/
[params.giscus]
enable = false
repo = "roninro/hugo-theme-puppet"
repo_id = "R_kgDOHuvyhw"
category = "General"
category_id = "DIC_kwDOHuvyh84CQjDo"
input_position = "top"
theme = "light_tritanopia"
lang = "en"