theme = "anatole"

[params]
title = "My Blog"
author = "SpinDev"
description = "Some insights in my work and my life."
keywords = "DevOps, GitHub, Azure DevOps, GitHub Pages, Azure"
profilePicture = "images/logo.png"
copyright = "SpinDev 2022-{{ YEAR }}"
displayMode = "dark"
contentratio = 0.7
singleDateFormat = "02.01.2006"
indexDateFormat = "02.01.2006"
listDateFormat = "02.01.2006"
readMore = true
rssFullContent = true
favicon = "favicons/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/spindev/"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://de.linkedin.com/in/till-spindler-78207024b"

[[params.socialIcons]]
icon = "fas fa-certificate"
title = "credly"
url = "https://credly.com/users/till-spindler/badges"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:hello@spindev.org"

[[params.socialIcons]]
icon = "fas fa-rss"
title = "rss"
url = "/index.xml"

mainSections = ["posts"]
enableEmoji = true
enableRobotsTXT = true
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[mermaid]
enable = true

[menu]
[[menu.main]]
name = "Home"
identifier = "home"
weight = 100
url = "/"

[[menu.main]]
name = "Posts"
weight = 200
identifier = "post"
url = "/post/"

[[menu.main]]
name = "Friends"
weight = 300
identifier = "friends"
url = "/friends/"

[[menu.main]]
name = "About"
weight = 400
identifier = "about"
url = "/about/"

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[related]
  includeNewer = true
  threshold = 80
  toLower = true
[[related.indices]]
  name = 'keywords'
  weight = 100
[[related.indices]]
  name = 'tags'
  weight = 80

